version: "2.1"

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  
  app:
   build: .
   container_name: my-node-app
   restart: always
   depends_on:
     - redis
   environment:
     - REDIS_HOST=redis
     - REDIS_PORT=6379
     - NEW_RELIC_APP_NAME=my-node-app
     - NEW_RELIC_LICENSE_KEY=4dd64769450b22a52544c036e908b6dfFFFFNRAL
     - NEW_RELIC_LOG_LEVEL=info
   ports:
     - "3006:3008"    