version: "2.1"

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  
  app:
   build: .
   container_name: my-node-app
   restart: always
   depends_on:
     - redis
   environment:
     - REDIS_HOST=redis
     - REDIS_PORT=6379
   ports:
     - "3006:3008"    